[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = false
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "paris"

# Deploy script configuration for Yellow Network
[rpc_endpoints]
base = "https://base-mainnet.g.alchemy.com/v2/WhI4CLoqy0ycLxPPoYwSx"

[etherscan]
base = { key = "1VRXFBKHA8BAM9GFW3BT668EDPPBYQK6V9", url = "https://api.basescan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
